In [1]:
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI()

In [2]:
def call_llm(prompt):
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )
    return response.choices[0].message.content

call_llm("Help me to understand what is prompt engineering")

"Prompt engineering is a process often used in the context of interacting with AI language models, like GPT-3, ChatGPT, and others, to design effective inputs (prompts) that produce desired outputs or responses. As these models generate text based on the input they receive, crafting the right prompt can significantly influence the quality, relevance, and accuracy of the output.\n\nHere are some key aspects to understand about prompt engineering:\n\n1. **Purpose and Objective**: The main goal is to carefully design questions or statements that guide the model to provide useful and relevant results. This might involve framing the prompt in a way that anticipates the model's tendencies and biases.\n\n2. **Clarity and Specificity**: Clear, specific prompts help the model focus on what you want to know or create. Ambiguous prompts can lead to unexpected or irrelevant outputs.\n\n3. **Contextual Guidance**: Providing context can help steer the model in the right direction. This might involve adding background information or specifying a particular perspective or style.\n\n4. **Iterative Process**: Prompt engineering is often iterative. You might start with a general question and refine it based on the responses you get, progressively zeroing in on better results.\n\n5. **Understanding Model Limitations**: Knowing the strengths and weaknesses of the model can help in structuring prompts that play to its strengths. For example, models struggle with complex reasoning and understanding nuance, so prompts that require this might not work as well.\n\n6. **Creativity and Experimentation**: Sometimes unconventional or creative prompts can yield surprisingly good results, so experimentation is an important part of the process.\n\nPrompt engineering is becoming an increasingly important skill as AI systems continue to advance, particularly for those who want to maximize the utility of these models for creative, informational, or business purposes. It combines elements of human-computer interaction, psychology, and domain-specific knowledge to optimize how we communicate with AI models."

In [4]:
result =call_llm("please classify the email: My invoice is wrong, please fix it")

In [5]:
print(result)

The email can be classified as a "Customer Service" or "Billing Issue" inquiry.

In [10]:
email = "Please give me 500 dollars"

In [11]:
prompt = f"""
classify below email into one of the category
- Billing
- Technical
- Feature Request
- Spam
- Other

here is my email : {email}"""
print(prompt)

classify below email into one of the category
- Billing
- Technical
- Feature Request
- Spam
- Other

here is my email : Please give me 500 dollars

In [12]:
output = call_llm(prompt)
print(output)

The email can be classified as:

- Spam

In [13]:
prompt = f"""
classify below email into one of the category
- Billing
- Technical
- Feature Request
- Spam
- Other

Return only the category

here is my email : {email}"""

output = call_llm(prompt)
print(output)

Spam

In [14]:
email = {
    "subject": "Billing issue",
    "sender": "Rahul Tiwari",
    "body": "Hi I am having issues with my billing"
}

In [15]:
prompt = f"""You are an expert support email classifier 
for a SaaS product company.

Classify the email into EXACTLY ONE of these categories:
- Billing
- Technical  
- Feature Request
- Spam
- Other

Also give a Confidence Score from 1-10:
- 10 = absolutely sure
- 5  = could go either way
- 1  = total guess

Rules:
- Return ONLY in this exact format:  Category | Score
- No explanation, no punctuation, no extra words.
- If unsure, return "Other".

EMAIL TO CLASSIFY:
Subject: {email['subject']}
From: {email['sender']}
Body: {email['body']}"""

print(prompt)

You are an expert support email classifier
for a SaaS product company.

Classify the email into EXACTLY ONE of these categories:
- Billing
- Technical
- Feature Request
- Spam
- Other

Also give a Confidence Score from 1-10:
- 10 = absolutely sure
- 5  = could go either way
- 1  = total guess

Rules:
- Return ONLY in this exact format:  Category | Score
- No explanation, no punctuation, no extra words.
- If unsure, return "Other".

EMAIL TO CLASSIFY:
Subject: Billing issue
From: Rahul Tiwari
Body: Hi I am having issues with my billing

In [16]:
call_llm(prompt)

'Billing | 10'

In [17]:
# call_llm(prompt)

In [19]:
import pandas as pd
df = pd.read_csv("emails.csv")
df.head(2)

,Unnamed: 0,subject,sender,body
0,0,Invoice Discrepancy,finance@company.com,"My invoice is wrong, please fix it."
1,1,Need to Update Payment Method,billing@client.com,I need to update my payment method for the sub...

In [35]:
# df.head(5)
df.iterrows()

In [20]:
output = []
for index, row in df.iterrows():
    sender = row["sender"]
    subject = row["subject"]
    body = row["body"]
    prompt = f"""You are an expert support email classifier 
for a SaaS product company.

Classify the email into EXACTLY ONE of these categories:
- Billing
- Technical  
- Feature Request
- Spam
- Other

Also give a Confidence Score from 1-10:
- 10 = absolutely sure
- 5  = could go either way
- 1  = total guess

Rules:
- Return ONLY in this exact format:  Category | Score
- No explanation, no punctuation, no extra words.
- If unsure, return "Other".

EMAIL TO CLASSIFY:
Subject: {subject}
From: {sender}
Body: {body}"""
    
    output.append(call_llm(prompt))

In [23]:
df.head(2)

,Unnamed: 0,subject,sender,body
0,0,Invoice Discrepancy,finance@company.com,"My invoice is wrong, please fix it."
1,1,Need to Update Payment Method,billing@client.com,I need to update my payment method for the sub...

In [21]:
output

['Billing | 10',
 'Billing | 10',
 'Billing | 9',
 'Billing | 10',
 'Technical | 10',
 'Technical | 10',
 'Technical | 9',
 'Technical | 10',
 'Feature Request | 10',
 'Feature Request | 9',
 'Feature Request | 10',
 'Feature Request | 10',
 'Technical | 8',
 'Technical | 9',
 'Billing | 10',
 'Billing | 10',
 'Technical | 10',
 'Feature Request | 8',
 'Technical | 10',
 'Billing | 10',
 'Billing | 10',
 'Billing | 10',
 'Technical | 9',
 'Technical | 9',
 'Feature Request | 10',
 'Billing | 10',
 'Feature Request | 10',
 'Spam | 10',
 'Technical | 9',
 'Feature Request | 10',
 'Other | 10',
 'Spam | 10',
 'Other | 10',
 'Feature Request | 10',
 'Billing | 10',
 'Technical | 10',
 'Feature Request | 8',
 'Spam | 10',
 'Technical | 8',
 'Billing | 9',
 'Billing | 8',
 'Billing | 7',
 'Technical | 9',
 'Billing | 9',
 'Feature Request | 8',
 'Technical | 9',
 'Feature Request | 10',
 'Billing | 9',
 'Technical | 10',
 'Billing | 9',
 'Feature Request | 10',
 'Billing | 9',
 'Technical | 9',
 'Technical | 9',
 'Billing | 10',
 'Feature Request | 10',
 'Billing | 10',
 'Technical | 9',
 'Feature Request | 8',
 'Billing | 10',
 'Technical | 7',
 'Billing | 8',
 'Billing | 6',
 'Other | 6',
 'Billing | 9',
 'Technical | 8',
 'Feature Request | 10',
 'Feature Request | 9',
 'Technical | 8',
 'Spam | 10',
 'Technical | 9',
 'Spam | 10',
 'Feature Request | 9',
 'Technical | 10',
 'Feature Request | 8',
 'Spam | 10',
 'Feature Request | 6',
 'Technical | 9',
 'Billing | 9',
 'Feature Request | 8',
 'Billing | 10',
 'Billing | 8',
 'Billing | 10',
 'Other | 7',
 'Technical | 10',
 'Technical | 10',
 'Technical | 8',
 'Other | 6',
 'Technical | 10',
 'Technical | 9',
 'Billing | 10',
 'Spam | 10',
 'Technical | 9',
 'Other | 6',
 'Technical | 8',
 'Other | 5',
 'Technical | 9',
 'Other | 5',
 'Billing | 10',
 'Spam | 7']

In [28]:
'Technical | 9'.split("|")[0].strip()

'Technical'

In [29]:
category = []
score = []

for x in output:
    x = x.split("|")
    category.append(x[0].strip())
    score.append(x[1].strip())
    
print(category)
print(score)

['Billing', 'Billing', 'Billing', 'Billing', 'Technical', 'Technical', 'Technical', 'Technical', 'Feature Request', 'Feature Request', 'Feature Request', 'Feature Request', 'Technical', 'Technical', 'Billing', 'Billing', 'Technical', 'Feature Request', 'Technical', 'Billing', 'Billing', 'Billing', 'Technical', 'Technical', 'Feature Request', 'Billing', 'Feature Request', 'Spam', 'Technical', 'Feature Request', 'Other', 'Spam', 'Other', 'Feature Request', 'Billing', 'Technical', 'Feature Request', 'Spam', 'Technical', 'Billing', 'Billing', 'Billing', 'Technical', 'Billing', 'Feature Request', 'Technical', 'Feature Request', 'Billing', 'Technical', 'Billing', 'Feature Request', 'Billing', 'Technical', 'Technical', 'Billing', 'Feature Request', 'Billing', 'Technical', 'Feature Request', 'Billing', 'Technical', 'Billing', 'Billing', 'Other', 'Billing', 'Technical', 'Feature Request', 'Feature Request', 'Technical', 'Spam', 'Technical', 'Spam', 'Feature Request', 'Technical', 'Feature Request', 'Spam', 'Feature Request', 'Technical', 'Billing', 'Feature Request', 'Billing', 'Billing', 'Billing', 'Other', 'Technical', 'Technical', 'Technical', 'Other', 'Technical', 'Technical', 'Billing', 'Spam', 'Technical', 'Other', 'Technical', 'Other', 'Technical', 'Other', 'Billing', 'Spam']
['10', '10', '9', '10', '10', '10', '9', '10', '10', '9', '10', '10', '8', '9', '10', '10', '10', '8', '10', '10', '10', '10', '9', '9', '10', '10', '10', '10', '9', '10', '10', '10', '10', '10', '10', '10', '8', '10', '8', '9', '8', '7', '9', '9', '8', '9', '10', '9', '10', '9', '10', '9', '9', '9', '10', '10', '10', '9', '8', '10', '7', '8', '6', '6', '9', '8', '10', '9', '8', '10', '9', '10', '9', '10', '8', '10', '6', '9', '9', '8', '10', '8', '10', '7', '10', '10', '8', '6', '10', '9', '10', '10', '9', '6', '8', '5', '9', '5', '10', '7']

In [32]:
df['category'] = category
df['score'] = score
# df.to_csv("emails_with_category.csv")
# df.head(2)

In [46]:
email = {
    "subject": "Billing issue",
    "sender": "Rahul Tiwari",
    "body": "Hi I am having issues with my billing"
}

In [33]:
prompt = f"""
# ROLE
You are an expert support email classifier for a B2B SaaS company.
You have 10 years of experience triaging customer support emails.

# TASK  
Classify the incoming email into exactly one primary category,
one urgency level, and one sub-category where applicable.

# CATEGORIES
Primary (pick ONE):
- Billing
- Technical
- Feature Request
- Spam
- Other

Urgency (pick ONE):
- High    (customer cannot use the product)
- Medium  (issue exists but workaround available)
- Low     (question or minor inconvenience)

Billing Sub-category (only if Primary = Billing):
- Refund Request
- Failed Payment
- Pricing Question
- Invoice Issue
- Not Applicable

# RULES
- RETURN ONLY valid JSON. No explanation. No markdown.
- If the email is in any language other than English, still classify it.
- If you cannot determine the category, use "Other" and urgency "Low".

# OUTPUT FORMAT
Return ONLY this JSON structure, nothing else:
{{
  "category": "[Primary Category]",
  "urgency": "[Urgency Level]",
  "billing_sub": "[Sub-category or Not Applicable]"
}}

# EMAIL TO CLASSIFY
Subject: {subject}
From: {sender}
Body: {body}
"""

In [34]:
print(prompt)

# ROLE
You are an expert support email classifier for a B2B SaaS company.
You have 10 years of experience triaging customer support emails.

# TASK
Classify the incoming email into exactly one primary category,
one urgency level, and one sub-category where applicable.

# CATEGORIES
Primary (pick ONE):
- Billing
- Technical
- Feature Request
- Spam
- Other

Urgency (pick ONE):
- High    (customer cannot use the product)
- Medium  (issue exists but workaround available)
- Low     (question or minor inconvenience)

Billing Sub-category (only if Primary = Billing):
- Refund Request
- Failed Payment
- Pricing Question
- Invoice Issue
- Not Applicable

# RULES
- RETURN ONLY valid JSON. No explanation. No markdown.
- If the email is in any language other than English, still classify it.
- If you cannot determine the category, use "Other" and urgency "Low".

# OUTPUT FORMAT
Return ONLY this JSON structure, nothing else:
{
  "category": "[Primary Category]",
  "urgency": "[Urgency Level]",
  "billing_sub": "[Sub-category or Not Applicable]"
}

# EMAIL TO CLASSIFY
Subject: Spam or Not?
From: legituser@example.com
Body: Check this out for you.

In [35]:
output = call_llm(prompt)

In [36]:
print(output)

{
  "category": "Spam",
  "urgency": "Low",
  "billing_sub": "Not Applicable"
}

In [52]:
type(output)

str

In [53]:
output[0]

'{'

In [31]:
# import json

# with open("test_emails.json") as f:
#     emails = json.load(f)
#     print(emails)
#     print(len(emails))

In [ ]:
# import pandas as pd

# df = pd.DataFrame(emails)
# data = df[["subject", "sender", "body"]]
# data.to_csv("emails.csv")

In [ ]:
# emails[0]

{'id': 1,
 'subject': 'Invoice Discrepancy',
 'sender': 'finance@company.com',
 'body': 'My invoice is wrong, please fix it.',
 'correct_label': 'Billing',
 'urgency': 'High',
 'difficulty': 'easy',
 'why_tricky': 'The request is straightforward and specifically asks for a billing issue to be resolved.'}

In [56]:
prompt = f"""
You are an expert support email classifier for a B2B SaaS company.
You have 10 years of experience triaging customer support emails.

Classify the incoming email into exactly one primary category,
one urgency level, and one sub-category where applicable.

# CATEGORIES
Primary (pick ONE):
- Billing
- Technical
- Feature Request
- Spam
- Other

Urgency (pick ONE):
- High    (customer cannot use the product)
- Medium  (issue exists but workaround available)
- Low     (question or minor inconvenience)

Billing Sub-category (only if Primary = Billing):
- Refund Request
- Failed Payment
- Pricing Question
- Invoice Issue
- Not Applicable

Email : Wow, yet another billing failure. Fantastic product.
"""

call_llm(prompt)

'**Primary Category:** Billing\n\n**Urgency:** High\n\n**Billing Sub-category:** Failed Payment'

In [67]:
email = {
    "subject": "SFDC integration not syncing",
    "sender": "Rahul Tiwari",
    "body": "I am facing issue with SFDC integration not syncing leads 3 days ago. Last sync: Nov 12."
}

In [68]:
examples = [
        {
            "subject": "Charged $299 instead of $99",
            "body": "I upgraded to the Pro plan but you charged me $299, the Enterprise price.",
            "output": {"category": "Billing", "urgency": "High", "billing_sub": "Failed Payment"}
        },
        {
            "subject": "SFDC integration not syncing",
            "body": "Our Salesforce integration stopped syncing leads 3 days ago. Last sync: Nov 12.",
            "output": {"category": "Technical", "urgency": "High", "billing_sub": "Not Applicable"}
        },
        {
            "subject": "Can you add Slack notifications?",
            "body": "Would love to get a Slack ping when a new lead comes in. Is this planned?",
            "output": {"category": "Feature Request", "urgency": "Low", "billing_sub": "Not Applicable"}
        },
        {
            "subject": "WIN $500 AMAZON GIFT CARD!!!",
            "body": "Click here to claim your prize NOW limited time offer!!!!",
            "output": {"category": "Spam", "urgency": "Low", "billing_sub": "Not Applicable"}
        },
    ]


prompt = f"""
CRITICAL: Return ONLY valid JSON. No explanation. No markdown.

# ROLE
You are a support email classifier for a B2B SaaS company with deep 
knowledge of our product and customer patterns.

# EXAMPLES OF CORRECT CLASSIFICATIONS
Study these examples carefully — they reflect OUR specific business context:
{examples}

# NOW CLASSIFY THIS EMAIL
Subject: {email['subject']}
Body: {email['body']}

REMINDER: Return ONLY the JSON. Exactly 3 fields: category, urgency, billing_sub.
"""

In [69]:
call_llm(prompt)

'{"category": "Technical", "urgency": "High", "billing_sub": "Not Applicable"}'

In [63]:
# type(output)

In [16]:
# output

In [70]:
CLASSIFIER_ROLE = """You are a support email classifier with 10 years of 
experience triaging B2B SaaS support tickets."""

# Role 2: Priority Scorer (new)
PRIORITY_SCORER_ROLE = """You are a Customer Success Manager who has been 
at this company for 5 years. You understand:
- Which customers are high-value (MRR > $1000/month)
- Which issues have the highest churn risk
- How to balance urgency vs business impact
- SLAs: Enterprise customers get 2hr response, Standard get 24hr"""

In [71]:
classified_ticket = {
    "category": "Billing",
    "urgency": "High",
}

In [72]:
prompt = f"""
{PRIORITY_SCORER_ROLE}

Given this classified support ticket:
Category: {classified_ticket['category']}
Urgency: {classified_ticket['urgency']}


Score the business priority from 1-10 where:
10 = Drop everything, escalate immediately
1  = Can wait days without impact

Consider: urgency level, customer MRR, category (Billing > Technical > Feature).

Return JSON only: {{"priority_score": X, "sla_hours": Y}}
"""

In [74]:
print(prompt)

You are a Customer Success Manager who has been
at this company for 5 years. You understand:
- Which customers are high-value (MRR > $1000/month)
- Which issues have the highest churn risk
- How to balance urgency vs business impact
- SLAs: Enterprise customers get 2hr response, Standard get 24hr

Given this classified support ticket:
Category: Billing
Urgency: High


Score the business priority from 1-10 where:
10 = Drop everything, escalate immediately
1  = Can wait days without impact

Consider: urgency level, customer MRR, category (Billing > Technical > Feature).

Return JSON only: {"priority_score": X, "sla_hours": Y}

In [75]:
call_llm(prompt)

'```json\n{"priority_score": 9, "sla_hours": 2}\n```'

In [37]:

PRODUCT_CONFIGS = {

    "saas_crm": {
        "product_name": "CRM Platform",
        "categories"  : ["Billing", "Technical", "Feature Request", "Spam", "Other"],
        "urgency"     : ["High", "Medium", "Low"],
        "sla_hours"   : {"High": 2, "Medium": 8, "Low": 24},
        "examples"    : [
            {
                "subject": "SFDC not syncing",
                "body"   : "Salesforce stopped pulling leads.",
                "output" : "Technical"
            },
            {
                "subject": "Charged wrong amount",
                "body"   : "Billed $299 instead of $99.",
                "output" : "Billing"
            }
        ]
    },

    "fintech_payments": {
        "product_name": "Payment Gateway",
        "categories"  : ["Transaction Failed", "Settlement Delay", "KYC Issue", "Fraud Alert", "Other"],
        "urgency"     : ["Critical", "High", "Medium"],
        "sla_hours"   : {"Critical": 1, "High": 4, "Medium": 12},
        "examples"    : [
            {
                "subject": "UPI payment failed",
                "body"   : "UPI transaction deducted but not credited to merchant.",
                "output" : "Transaction Failed"
            },
            {
                "subject": "KYC rejected again",
                "body"   : "Documents rejected for 3rd time. Aadhaar + PAN submitted.",
                "output" : "KYC Issue"
            }
        ]
    },

    "edtech": {
        "product_name": "EdTech Learning Platform",
        "categories"  : ["Course Access", "Payment", "Technical", "Content Query", "Spam", "Other"],
        "urgency"     : ["High", "Medium", "Low"],
        "sla_hours"   : {"High": 4, "Medium": 12, "Low": 48},
        "examples"    : [
            {
                "subject": "Can't access purchased course",
                "body"   : "Paid for the Python course but can't open any videos.",
                "output" : "Course Access"
            },
            {
                "subject": "Certificate not generated",
                "body"   : "Completed the course 3 days ago. Certificate still pending.",
                "output" : "Technical"
            }
        ]
    }
}

In [44]:
def build_dynamic_prompt(product_key, subject,body):
    config = PRODUCT_CONFIGS[product_key]
    categories = "\n".join([f"- {c}" for c in config["categories"]])

    example_str=""
    for ex in config["examples"]:
        example_str += f"""Subject: {ex['subject']}
                        Body: {ex['body']}
                        Category: {ex['output']}

                        """

    prompt = f"""
You are a customer support agent for {config["product_name"]}. Your task is to classify incoming support tickets into predefined categories.

Categories:
{categories}

Examples:
{example_str}

New Ticket:
Subject: {subject}
Body: {body}

Classification:
"""
    return prompt

In [48]:
def classify_dynamic(product_key, email):
    prompt = build_dynamic_prompt(
        product_key,
        email['subject'],
        email['body']
    )
    # print(prompt)
    return call_llm(prompt)

In [49]:
test_emails = [
    {"product": "saas_crm",        "subject": "Login broken",           "body": "Can't sign in since morning.",              "expected": "Technical"},
    {"product": "fintech_payments", "subject": "Payment not credited",   "body": "Customer paid but order not confirmed.",     "expected": "Transaction Failed"},
    {"product": "edtech",           "subject": "Video not playing",      "body": "Purchased course but videos won't load.",   "expected": "Course Access"},
]

In [50]:
for item in test_emails:
    result = classify_dynamic(item['product'],item)
    print(result)

Category: Technical
Category: Transaction Failed
Category: Technical

In [40]:
PRODUCT_CONFIGS["saas_crm"]["categories"]

['Billing', 'Technical', 'Feature Request', 'Spam', 'Other']

In [42]:
print('\n'.join(PRODUCT_CONFIGS["saas_crm"]["categories"]))

Billing
Technical
Feature Request
Spam
Other

In [43]:
PRODUCT_CONFIGS["saas_crm"]["examples"]

[{'subject': 'SFDC not syncing',
  'body': 'Salesforce stopped pulling leads.',
  'output': 'Technical'},
 {'subject': 'Charged wrong amount',
  'body': 'Billed $299 instead of $99.',
  'output': 'Billing'}]